services:
  app:
    build: .
    container_name: effectiveMobile_test_app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "8080:8080"
    networks:
      - mylocal
  db:
    image: postgres:16.2
    container_name: effectiveMobile_test_db
    hostname: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 2
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - mylocal
networks:
  mylocal:
    driver: bridge
